#
# |-----| |-----| |-----| |-----| |-----| |-----| |-----| |-----| |-----|
#    |    |       |     | |       |     | |     | |     |    |    |
#    |    |-----| |-----| |---|   |-----| |     | |-----|    |    |-----|
#    |          | |   \   |       |       |     | |   \      |          |
#    |    |-----| |    \  |-----| |       |-----| |    \     |    |-----|
#                                                      made by Todesstoss
#

#⮟ PLUGIN ⮟

default-server-language: 'en_US' # all language files are in '/plugins/TSReports/locales'
blacklisted: # players who cannot report others
  - example1
  - example2
adminCommandAliases: # aliases for the admin command
  - reports
  - reps
  - tsreports
reportCommandAliases: # aliases for the report command
  - report
  - rep
  - blame
protocolize: false # to be able to use the report inventory, this setting must be set to 'true'
debug: false  # when having trouble to find a bug use this
updateChecker: true # enables / disables the updater of the plugin

#⮟ GENERAL ⮟

#⮟ determines how many reports are on a page, when using the list command
listPageLimit: 10

#⮟ determines how long a player cannot report after reporting
reportCooldown: 60

#⮟ determines how many reports it takes until a certain level is reached
reportsTillMed: 25
reportsTillHigh: 50

#⮟ DATABASE ⮟
mysql:
  enabled: false # if disabled H2 will be used
  host: localhost
  database: minecraft
  username: player
  password: abc123
  port: 3306 # default mysql port